import { useLocation, useNavigate } from "react-router-dom";
import { useEffect } from "react";

const data = {
    "success": true,
    "spec_code": 6376,
    "common_name": "goldfish",
    "data": {
        "identifier": "FB-6376",
        "source": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "Kingdom": "Animalia",
        "Phylum": "Chordata",
        "Class": "Teleostei",
        "Order": "Cypriniformes",
        "Family": "Cyprinidae",
        "Genus": "Carassius",
        "ScientificName": "Carassius gibelio (Bloch, 1782)",
        "commonName": "Karas srebrzysty",
        "commonName_2": "karaś srebrzysty",
        "commonName_3": "Karas srebrzysty a. japonczyk",
        "commonName_4": "Karasi prusian",
        "commonName_5": "Srebarna karracuda",
        "commonName_6": "Karas stříbřitý",
        "commonName_7": "Karas stribrity eurasijsky",
        "commonName_8": "Karas striebristy",
        "commonName_9": "Damkaruds",
        "commonName_10": "Damkarusse",
        "commonName_11": "Giebel",
        "commonName_12": "sølvkaruds",
        "commonName_13": "Giebel",
        "commonName_14": "Silberkarausche",
        "commonName_15": "Gibel carp",
        "commonName_16": "Giebel",
        "commonName_17": "Giebel carp",
        "commonName_18": "Goldfish",
        "commonName_19": "Golden carp",
        "commonName_20": "Prussian carp",
        "commonName_21": "hõbekoger",
        "commonName_22": "Hopearuutana",
        "commonName_23": "Carassin argenté",
        "commonName_24": "Ezüst kárász",
        "commonName_25": "sudrabkarūsa",
        "commonName_26": "sidabrinis karosas",
        "commonName_27": "Cеребряный карась",
        "commonName_28": "Obyknovennyi serebryanyi karas'",
        "commonName_29": "Serebreanyi karas",
        "commonName_30": "Serebryanyi karas",
        "commonName_31": "серебристый карась",
        "commonName_32": "серебряный карась",
        "commonName_33": "Karas zlatas",
        "commonName_34": "Karaš zlataš",
        "commonName_35": "silverruda",
        "commonName_36": "Çin sazaru",
        "commonName_37": "Kirmizi havuz baligi",
        "commonName_38": "Karas sriblyastyi",
        "commonName_39": "Карась сріблястий",
        "commonName_40": "Карась срібний",
        "commonName_41": "Cá Diếc bạc",
        "commonName_42": "Caracuda argintie",
        "commonName_43": "Caras",
        "commonName_44": "Caras-argintiu",
        "commonName_45": "Crap-caras",
        "commonName_46": "Giebel",
        "commonName_47": "Petalouda",
        "commonName_48": "Srebrni koreselj",
        "commonName_49": "Zlatni koreselj",
        "commonName_50": "Ιταλικό",
        "commonName_51": "Πεταλούδα",
        "commonName_52": "Кумуштой таман балык",
        "commonName_53": "銀鯽",
        "commonName_54": "银鲫",
        "synonym": "Carassius auratus gibelio (Bloch, 1782)",
        "synonym_2": "Carassius auratus gibelio vovkii Johansen, 1945",
        "synonym_3": "Carassius bucephalus Heckel, 1837",
        "synonym_4": "Carassius ellipticus Heckel, 1848",
        "synonym_5": "Carassius vulgaris kolenty Dybowski, 1877",
        "synonym_6": "Carassius vulgaris ventrosus Walecki, 1863",
        "synonym_7": "Cyprinus amarus Koch, 1840",
        "synonym_8": "Cyprinus gibelio Bloch, 1782",
        "created": "1992-08-31",
        "modified": "2024-01-25",
        "reference": "Herre, A.W.C.T.0 Check list of Philippine fishes. Res. Rep. U.S. Fish Wild. Serv. (20):1-977. (Ref. 280)",
        "reference_2": "Muus, B.J. and P. Dahlström0 Süßwasserfische. BLV Verlagsgesellschaft, München. 224 p. (Ref. 556)",
        "reference_3": "Blanc, M., J.-L. Gaudet, P. Banarescu and J.-C. Hureau0 European inland water fish. A multilingual catalogue. Fishing News (Books) Ltd., London. (Ref. 683)",
        "reference_4": "Berg, L.S.0 Freshwater fishes of the U.S.S.R. and adjacent countries. volume 2, 4th edition. Israel Program for Scientific Translations Ltd, Jerusalem. (Russian version published 1949). (Ref. 1441)",
        "reference_5": "Welcomme, R.L.0 International introductions of inland aquatic species. FAO Fish. Tech. Pap. 294. 318 p. (Ref. 1739)",
        "reference_6": "Baensch, H.A. and R. Riehl0 Aquarien atlas. Bd. 3. Melle: Mergus, Verlag für Natur-und Heimtierkunde, Germany. 1104 p. (Ref. 2059)",
        "reference_7": "Hureau, J.-C.0 La base de données GICIM: Gestion informatisée des collections ichthyologiques du Muséum. p. 225-227. In Atlas Préliminaire des Poissons d'Eau Douce de France. Conseil Supérieur de la Pêche, Ministère de l'Environnement, CEMAGREF et Muséum national d'Histoire naturelle, Paris. (Ref. 4517)",
        "reference_8": "Chiba, K., Y. Taki, K. Sakai and Y. Oozeki0 Present status of aquatic organisms introduced into Japan. p. 63-70. In S.S. De Silva (ed.) Exotic aquatic organisms in Asia. Proceedings of the Workshop on Introduction of Exotic Aquatic Organisms in Asia. Spec. Publ. Asian Fish. Soc. 3, 154 p. (Ref. 6094)",
        "reference_9": "Grabda, E. and T. Heese0 Polskie nazewnictwo popularne kraglouste i ryby. Cyclostomata et Pisces. Wyzsza Szkola Inzynierska w Koszalinie. Koszalin, Poland. 171 p. (in Polish). (Ref. 6313)",
        "reference_10": "Vasil'ev, V.P.0 Chromosome numbers in fish-like vertebrates and fish. J. Ichthyol. 20(3):1-38. (Ref. 8973)",
        "reference_11": "Economidis, P.S.0 Catalogue of the fishes of Greece. Reprinted from Hellenic Oceanology and Limnology, Praktika of the Inst. of Ocean. and Fishing Research, vol. 11 (1972). (Ref. 9057)",
        "reference_12": "Kamilov, G. and Z.U. Urchinov0 Fish and fisheries in Uzbekistan under the impact of irrigated agriculture. p. 10-41 In T. Petr (ed.) Inland fisheries under the impact of irrigated agriculture:Central Asia. FAO Fisheries Circular No. 894. (Ref. 11145)",
        "reference_13": "Cui, J., X. Ren and Q. Yu0 Nuclear DNA content variation in fishes. Cytologia 56:425-429. (Ref. 12384)",
        "reference_14": "Anonymous0 Fish registrations within the museum database of the Vertebrate Section of the Royal Museum for Central Africa. MRAC, Tervuren, Belgium. (Ref. 12818)",
        "reference_15": "Li, Y., K. Li, Z. Gui and D. Zhou0 Studies on the karyotypes of Chinese cyprinid fishes. 6. Karyotypes of three tetraploid species in Barbinae and one tetraploid species in Cyprininae. Acta Genet. Sin. 12(4):302-308. (Ref. 13148)",
        "reference_16": "Bogutskaya, N.G. and A.M. Naseka0 Cyclostomata and fishes of Khanka Lake drainage area (Amur river basin). An annotated check-list with comments on taxonomy and zoogeography of the region. Zool. Inst. Russ. Acad. Sci. :89 p. (Ref. 13397)",
        "reference_17": "Kottelat, M.0 European freshwater fishes. An heuristic checklist of the freshwater fishes of Europe (exclusive of former USSR), with an introduction for non-systematists and comments on nomenclature and conservation. Biologia, Bratislava, 52/Suppl. 5:1-271. (Ref. 13696)",
        "reference_18": "Specziár, A., L. Tölg and P. Biró0 Feeding strategy and growth of cyprinids in the littoral zone of Lake Balaton. J. Fish Biol. 51(6):1109-1124. (Ref. 26323)",
        "reference_19": "Gerstmeier, R. and T. Romig0 Die Süßwasserfische Europas: für Naturfreunde und Angler. Franckh-Kosmos Verlag, Stuttgart, Germany. 368 p. (Ref. 27368)",
        "reference_20": "Kleanthidis, P.K., A.I. Sinis and K.I. Stergiou0 Length-weight relationships of freshwater fishes in Greece. Naga, ICLARM Q. 22(4):37-41. (Ref. 27610)",
        "reference_21": "Écoutin, J.-M. and J.-J. Albaret0 Length-weight relationship of 52 fish species from West African estuaries and lagoons. Cybium 27(1):3-9. (Ref. 28094)",
        "reference_22": "Penaz, M., P. Ráb and M. Prokes0 Cytological analysis, ginogenesis and early development of <i>Carassius auratus gibelio</i>. Prirodoved. pr. ustavu CSAV Brne. 13(7):38p. (Ref. 29604)",
        "reference_23": "Kobayasi, H., H. Ochi and N. Takeuchi0 Chromosome studies of the silver crucian carps (<i>Carassius auratus gibelio</i>) from valley of the Amur river, and their progenies. Jap. Women. Univ. J. (Home Economics). 20():83-88. (Ref. 29695)",
        "reference_24": "Rass, T.S.0 Fish. Vol. 4, Life of animals. V.E. Sokolov (ed.), Moscow: Prosveschenie. 575p. (Ref. 30503)",
        "reference_25": "Sal'nikov, V.B.0 Anthropogenic migration of fish in Turkmenistan. J. Ichthyol. 38(8):591-602. (Ref. 30700)",
        "reference_26": "Swedish Museum of Natural History0 Fish collection database of the Naturhistoriska riksmuseet (Swedish Museum of Natural History). Ichthyology Section, Department of Vertebrate Zoology, Swedish Museum of Natural History, Stockholm, Sweden. (Ref. 31402)",
        "reference_27": "Wu, H.L., K.-T. Shao and C.F. Lai (eds.)0 Latin-Chinese dictionary of fishes names. The Sueichan Press, Taiwan. 1028 p. (Ref. 31517)",
        "reference_28": "Specziar, A., P. Biro and L. Tolg0 Feeding and competition of five cyprinid fishes in different habitats of the Lake Balaton littoral zone, Hungary. Ital. J. Zool. 65:331-336. (Ref. 31897)",
        "reference_29": "Anonymous0 Fish collection database of the Natural History Museum, London (formerly British Museum of Natural History (BMNH)). Natural History Museum, London (formerly British Museum of Natural History (BMNH)). (Ref. 31982)",
        "reference_30": "Anonymous0 Systematic list of Estonian fishes. World Wide Web Electronic Publication, 14 January 2000. (Ref. 33247)",
        "reference_31": "Klinkhardt, M, M. Tesche and H. Greven0 Database of fish chromosomes. Westarp Wissenschaften. (Ref. 34370)",
        "reference_32": "Anonymous0 The icthyological collection of the Zoological Museum Hamburg (ZMH). Division of Ichthyology and Herpetology, Zoological Museum Hamburg (ZMH). (Ref. 35508)",
        "reference_33": "Economidis, P.S., E. Dimitriou, R. Pagoni, E. Michaloudi and L. Natsis0 Introduced and translocated fish species in the inland waters of Greece. Fish. Manage. Ecol. 7:239-250. (Ref. 35895)",
        "reference_34": "Winkler, H.M., K. Skora, R. Repecka, M. Ploks, A. Neelov, L. Urho, A. Gushin and H. Jespersen0 Checklist and status of fish species in the Baltic Sea. ICES CM 2000/Mini:11, 15 p. (Ref. 36252)",
        "reference_35": "Anonymous0 Fish collection database of the J.L.B. Smith Institute of Ichthyology, Grahamstown, South Africa. J.L.B. Smith Institute of Ichthyology, Grahamstown, South Africa. (Ref. 36670)",
        "reference_36": "Golani, D. and D. Mires0 Introduction of fishes to the freshwater system of Israel. Isr. J. Aquacult. / Bamidgeh 52(2):47-60. (Ref. 37616)",
        "reference_37": "Østergaard, T.A.S.0 List of freshwater fishes and common names. Personal communication (ID #575). (Ref. 37782)",
        "reference_38": "Li, S.0 Genetic characterization of major freshwater culture fishes in China. Shanghai Scientific & Technical Publishers, Shanghai, China, 233 p. (Ref. 37798)",
        "reference_39": "Anonymous0 Fish collection database of the National Museum of Natural History (Smithsonian Institution). Smithsonian Institution-Division of Fishes. (Ref. 38732)",
        "reference_40": "Banarescu, P.0 Pisces - Osteichthyes (pesti ganoizi si osisi). Editura Academiei Republicii Populare Romîne, Bucuresti. 962 p. (Ref. 39150)",
        "reference_41": "Kukuradze, A.M. and L.F. Mariyash0 Information on the ecology of wild goldfish (<i>Carassius auritus gibelio</i>) in the lower reaches of the Danube. J. Ichthyol. 15(3):409-415. (Ref. 39176)",
        "reference_42": "Keith, P. and J. Allardi (coords.)0 Atlas des poissons d'eau douce de France. Muséum national d’Histoire naturelle, Paris. Patrimoines naturels, 47:1-387. (Ref. 40476)",
        "reference_43": "Anonymous0 Fish collection database of the Zoological Museum, University of Copenhagen. Zoological Museum, University of Copenhagen. (Ref. 40919)",
        "reference_44": "Savvaitova, K.A. and T. Petr0 Fish and fisheries in Lake Issyk-kul (Tien Shan), River Chu and Pamir lakes. p. 168-186. In T. Petr (ed.) Fish and fisheries at higher altitudes: Asia. FAO Fish. Tech. Pap. No. 385. FAO, Rome. 304 p. (Ref. 41059)",
        "reference_45": "Dulmaa, A.0 Fish and fisheries in Mongolia. p. 187-236. In T. Petr (ed.) Fish and fisheries at higher altitudes: Asia. FAO Fish. Tech. Pap. No. 385. FAO, Rome. 304 p. (Ref. 41072)",
        "reference_46": "Walker, K.F. and H.Z. Yang0 Fish and fisheries in western China. FAO Fish. Tech. Pap. 385:237-278. (Ref. 41093)",
        "reference_47": "Gabrielyan, B.K.0 An annotated checklist of freshwater fishes of Armenia. Naga, ICLARM Q. 24(3-4):23-29. (Ref. 41168)",
        "reference_48": "Economidis, P.S. and E. Koutrakis0 Common names of comercially important Hellenic marine organisms. Aristotle University, Unpublished Technical Report. (Ref. 41475)",
        "reference_49": "Economidis, P.S.0 Check list of freshwater fishes of Greece (recent status of threats and protection). Hellenic Society for the Protection of Nature, Special publication, 48 p. (Ref. 41624)",
        "reference_50": "Bobori, D.C., P.S. Economidis and E.G. Maurakis0 Freshwater fish habitat science and management in Greece. Aquatic Ecosystem Health and Management 4:381-391. (Ref. 41625)",
        "reference_51": "Cernisencu, I., M. Staras and I. Novadaru0 Studiul comparativ privind exploatarea populatillor de caras (<i>Carassius auratus gibelio</i>) din lacurile Razim si Puiu-Rosu. Analele Stiintifice ale Institutului-Delta Dunarii 3:233-242. (Ref. 41817)",
        "reference_52": "Cernisencu, I. and M. Staras0 Valorificarea durabila a resurselor piscicole - pricipiu de baza in practicarea pescutului in Delta Dunarii. Analele Stiintifice ale Institutului-Delta Dunarii. (Ref. 41818)",
        "reference_53": "Staras, M., I. Cernisencu and I. Navodaru0 Studiul cresterii principalelor specii de pesti din complexul Razim-Sinoe. Aquaropi, Galaxi, Romania. p. 417-420. (Ref. 41826)",
        "reference_54": "Spratte, S and U. Hartmann0 Fischartenkataster: Süßwasserfische und Neunaugen in Schleswig-Holstein. Ministerium für ländliche Räume, Landwirtschaft, Ernährung und Tourismus, Kiel Germany. 183 p. (Ref. 41851)",
        "reference_55": "Wolfram-Wais, A., G. Wolfram, B. Auer, E. Mikschi and A. Hain0 Feeding habits of two introduced fish species (<i>Lepomis gibbosus, Pseudorasbora parva</i>) in Neusiedler See (Austria), with special reference to chironomid larvae (Diptera: Chironomidae). Hydrobiologia 408/409:123-129. (Ref. 42249)",
        "reference_56": "Bobori, D.C., P.S. Economidis and E.G. Maurakis0 Freshwater fish habitat science and management in Greece. Aquatic Ecosystem Health and Management 4:381-391. (Ref. 42629)",
        "reference_57": "Bogutskaya, N.G. and A.M. Naseka0 An overview of nonindigenous fishes in inland waters of Russia. Proc. Zool. Inst. Russ. Acad. Sci. 296:21-30. (Ref. 45022)",
        "reference_58": "Bogutskaya, N.G.0 Common names of Russian freshwater fishes. Spreadsheet with cyrillic names made available for inclusion in FishBase. Unpublished. (Ref. 45043)",
        "reference_59": "Luo, Y. and P. Yue0 Cyprinidae: Cyprininae. p. 391-433. In P. Yue et al. (Eds). Fauna Sinica. Osteichthyes. Cypriniformes III. Science Press. Beijing. 1-661. (Ref. 45623)",
        "reference_60": "Salekhova, L.P., N.S. Kostenko, T.A. Bogachick and O.N. Minibaeva0 Composition of ichthyofauna in the region of the Karadag State Reserve (Black Sea). J. Ichthyol. 28(2):16-23. (Ref. 45714)",
        "reference_61": "Anonymous0 Fish collection of the Royal Ontario Museum. Royal Ontario Museum. (Ref. 47438)",
        "reference_62": "Wang, G.T., W.J. Yao, J.G. Wang and Y.S. Lu0 Occurrence of thelohanellosis caused by <i>Thelohanellus wuhanensis</i> (Mysoxporea) in juvenile allogynogenetic silver crucian carp, <i>Carassius auratus gibelio</i> (Bloch), with an observation on the efficacy of fumagillin as a therapeutant. J. Fish Dis. 24:57-60. (Ref. 47459)",
        "reference_63": "Bundesanstalt für Landwirtschaft und Ernährung0 Verzeichnis der Handelsbezeichnungen für Erzeugnisse der Fischerei und der Aquakultur. Retrieved 17 June 2003, from http://www.ble.de. (Ref. 47487)",
        "reference_64": "Ondrackova, M., P. Jurajda and M. Gelnar0 The distribution of <i>Posthodiplostomum cuticola</i> metacercariae in young-of-the-year cyprinid fishes. J. Fish Biol. 60(5):1355-1357. (Ref. 47806)",
        "reference_65": "Russian Academy of Sciences0 Catalog of vertebrates of Kamchatka and adjacent waters. Kamchatsky Pechatny Dvor, Petropavlovsk-Kamchatsky, Russia. 166 p. (Ref. 50610)",
        "reference_66": "Thiel, R., H. Cabral and M.J. Costa0 Composition, temporal changes and ecological guild classification of the ichthyofaunas of large European estuaries - a comparison between the Tagus (Portugal) and the Elbe (Germany). J. Appl. Ichthyol. 19(5):330-342. (Ref. 51031)",
        "reference_67": "Hanel, L. and J. Novák0 České názvy zivočichů V. Ryby a ryboviti obratlovci (Pisces) 3., maloústí (Gonorhynchiformes) - máloostní (Cypriniformes). Národní muzeum (zoologické oddělení), Praha. (Ref. 51055)",
        "reference_68": "Varjo, M., L. Koli and H. Dahlström0 Kalannimiluettelo (versio 10/03). Suomen Biologian Seura Vanamo Ry. (Ref. 51086)",
        "reference_69": "Riede, K.0 Global register of migratory species - from global to regional scales. Final Report of the R&D-Projekt 808 05 081. Federal Agency for Nature Conservation, Bonn, Germany. 329 p. (Ref. 51243)",
        "reference_70": "Carl, H.0 Danish fish names. Zoological Museum of Copenhagen. Unpublished. (Ref. 51471)",
        "reference_71": "Leggatt, R.A. and G.K. Iwama0 Occurrence of polyploidy in the fishes. Rev. Fish Biol. Fish. 13:237-246. (Ref. 51672)",
        "reference_72": "Institute of Hydrobiology, Academia Sinica, Shanghai Natural Museum and Ministry of Agriculture of China0 The freshwater fishes of China in coloured illustrations. Vol. 3. Institute of Hydrobiology, Academia Sinica and Shanghai Natural Museum and Ministry of Agriculture of China. Includes 188 colured photos in hardback, 166p. (Ref. 51717)",
        "reference_73": "FiCen0 Common freshwater fishes of Vietnam. Fisheries Information Center of Vietnam (FiCen). Sô 10 Nguyen Công Hoan-Ba Dinh-Há Nôi, Vietnam. Poster. (Ref. 51882)",
        "reference_74": "Ojaveer, E. and E. Pihu0 Estonian natural fish waters. p. 15-27. In E. Ojaveer, E. Pihu and T. Saat (eds.) Fishes of Estonia. Estonian Academy Publishers, Tallinn. (Ref. 52079)",
        "reference_75": "Ojaveer, E., E. Pihu and T. Saat0 Fishes of Estonia. Estonian Academy Publishers, Tallinn. 416 p. (Ref. 52093)",
        "reference_76": "Hanel, L.0 Komentovaný přehled mihulí a ryb české republiky. Bull. Lampetra V:27-67. (Ref. 54731)",
        "reference_77": "Hanel, L.0 The ichthyofauna of the Czech Republic: development and present state. Matthias Belivs Univ. Proc. 3(1):41-71. (Ref. 54732)",
        "reference_78": "Ma, X., X. Bangxi, W. Yindong and W. Mingxue0 Intentionally introduced and transferred fishes in China's inland waters. Asian Fish. Sci. 16(3&4):279-290. (Ref. 55380)",
        "reference_79": "Solarz, W.0 Alien Species in Poland. Institute of Nature Conservation, Polish Academy of Sciences website. (Ref. 55773)",
        "reference_80": "Innal, D. and F. Erk'akan0 Effects of exotic and translocated fish species in the inland waters of Turkey. Rev. Fish Biol. Fish. 16:39-50. (Ref. 57271)",
        "reference_81": "Kottelat, M.0 Fishes of Mongolia. A check-list of the fishes known to occur in Mongolia with comments on systematics and nomenclature. The World Bank, Washington, DC. 103 p. (Ref. 57778)",
        "reference_82": "Chinese Academy of Fishery Sciences0 Chinese aquatic germplasm resources database. http://zzzy.fishinfo.cn (Ref. 58108)",
        "reference_83": "Bogutskaya, N.G. and A.M. Naseka0 REGIONAL CHECK-LISTS: Don River Drainage Area. In Website and Database: \"Freshwater Fishes of Russia\": A Source of Information on the Current State of the Fauna. Zoological Institute RAS. (Ref. 58293)",
        "reference_84": "Bogutskaya, N.G. and A.M. Naseka0 REGIONAL CHECK-LISTS: Kuban River Drainage Area. In Website and Database: \"Freshwater Fishes of Russia\": A Source of Information on the Current State of the Fauna. Zoological Institute RAS. (Ref. 58296)",
        "reference_85": "Bogutskaya, N.G. and A.M. Naseka0 REGIONAL CHECK-LISTS: Volga River Drainage Area. In Website and Database: \"Freshwater Fishes of Russia\": A Source of Information on the Current State of the Fauna. Zoological Institute RAS. (Ref. 58297)",
        "reference_86": "Bogutskaya, N.G. and A.M. Naseka0 REGIONAL CHECK-LISTS: Amur River Drainage Area in Russia. In Website and Database: \"Freshwater Fishes of Russia\": A Source of Information on the Current State of the Fauna. Zoological Institute RAS. (Ref. 58298)",
        "reference_87": "Bogutskaya, N.G. and A.M. Naseka0 REGIONAL CHECK-LISTS: Sakhalin Island. In Website and Database: \"Freshwater Fishes of Russia\": A Source of Information on the Current State of the Fauna. Zoological Institute RAS. (Ref. 58299)",
        "reference_88": "Zhukov, P.I.0 Encyclopedia on ecology of freshwater fishes. Minsk, Nauka i tekhnika Press (in Russian). (Ref. 59038)",
        "reference_89": "Mastitsky, S.E., A.Y. Karatayev and L.E. Burlakova0 Aquatic invaders of Belarus: Alien species database. www.aliensinbelarus.com. Accessed 4 October 2007. (Ref. 59042)",
        "reference_90": "Kottelat, M. and J. Freyhof0 Handbook of European freshwater fishes. Publications Kottelat, Cornol and Freyhof, Berlin. 646 pp. (Ref. 59043)",
        "reference_91": "Tarkan, A.S., O. Gaygusuz, H. Acipinar, C. Gürsoy and M. Ozulug0 Length-weight relationship of fishes from the Marmara region (NW-Turkey). J. Appl. Ichthyol. 22:271-273. (Ref. 59105)",
        "reference_92": "Bartley, D.M. (comp./ed.)0 DIAS. Introduced species in fisheries and aquaculture: information for responsible use and control. CD-ROM. Rome (Italy): FAO. (Ref. 74657)",
        "reference_93": "Paschos, I., C. Nathanailides, A. Samara, E. Gouva and M. Tsoumani0 Presence of gibel carp (<i>Carasius auratus gibelio</i>) in Lake Pamvotis: Spawning behaviour characteristics and prospects for controling the population. p. 245-248. In Proceedings of the Tenth Ichthyological Congress, 18-22 October 2001, Chania, Greece. (in Greek with English abstract). (Ref. 74684)",
        "reference_94": "Papigioti, O., A. Tsikliras, V. Eleftheriou, I. Kagalou, R. Chortatou, I. Kladas and I. Leonardos0 Age, growth and reproduction of the allochthonus species <i>Carassius gibelio</i> (Bloch, 1972) in Lake Chimaditis (northen Greece). p. 149-151. In Proceedings of the Thirteenth Ichthyological Congress, 27-30 September 2007 , Mytilini, Greece. (in Greek with English abstract). (Ref. 74691)",
        "reference_95": "Leonardos, I., P. Katharios and C. Charisis0 Age, growth and mortality of <i>Carassius auratus gibelio</i> (Linnaeus, 1758) (Pisces: Cyprinidae) in Lake Lysimachia. p. 257-259. In Proceedings of the Tenth Ichthyological Congress, 18-22 October 2001, Chania, Greece. (in Greek with English abstract). (Ref. 74692)",
        "reference_96": "Kokkinakis, K.A., I.A. Sinis, E. Eleftheriadis and E. Koutrakis0 Seasons and areas of reproduction of the main fished spicies in Lake Volvi. p. 269-272. In Proceedings of the Tenth Ichthyological Congress, 18-22 October 2001, Chania, Greece. (in Greek with English abstract). (Ref. 74697)",
        "reference_97": "Balık, İ., R. Ozkok, H. Cubuk and R. Uysal0 Investigation of some biological characteristics of the silver crucian carp, <i>Carassius gibelio</i> (Bloch 1782) population in Lake Egirdir. Turk. J. Zool. 28:19-28. (Ref. 75137)",
        "reference_98": "Crivelli, A.J., G. Catsadorakis, M. Malakou and E. Rosecchi0 Fish and fisheries of the Prespa lakes. Hydrobiologia 351:107-125. (Ref. 75668)",
        "reference_99": "Verreycken, H., D. Anseeuw, G. Van Thuyne, P. Quataert and C. Belpaire0 The non-indigenous freshwater fishes of Flanders (Belgium): review, status and trends over the last decade. J. Fish Biol. 71(Suppl.D):160-172. (Ref. 79522)",
        "reference_100": "Konurbaev, A.O. and Timirkhanov S.R.0 Looking at fishes in Kyrgyzia. Central Asia. Daru Ltd. 120 p. (Ref. 79647)",
        "reference_101": "Wittenberg, R. (ed.).0 An inventory of alien species and their threat to biodiversity and economy in Switzerland. CABI Bioscience Switzerland Centre report to the Swiss Agency for Environment, Forests and Landscape. The environment in practice no. 0629. Federal Office for the Environment, Bern. 155 pp. (Ref. 79869)",
        "reference_102": "Machacek, H. (ed.)0 World Records Freshwater Fishing. www.fishing-worldrecords.com, June 2009. (Ref. 81828)",
        "reference_103": "Dhora, Dh.0 Regjistër I specieve të faunës së Shqipërisë 2010. Shkodër: Camaj-Pipa. 208 p. (Ref. 83428)",
        "reference_104": "Lusk, M.R., Luskova V. and L. Hanel0 Alien fish species in the Czech Republic and their impact on the native fish fauna. Folia Zool. 59(1):57-72. (Ref. 83969)",
        "reference_105": "Machacek, H. (ed.)0 World Records Freshwater Fishing. www.fishing-worldrecords.com, September 2010. (Ref. 85107)",
        "reference_106": "Dhora, Dh.0 Fjalor i emrave të kafshëve të Shqipërisë (Emri shkencor - Shqip - Anglisht) / Dictionary of animal names of Albania (Scientific names - Albanian - English). Camaj - Pipa. Shkodër, Albania. pp. 288. (Ref. 87029)",
        "reference_107": "AFMAFEWM (Austrian Federal Ministry of Agriculture, Forestry, Environment and Water Management)0 Checklist of species in Austria. Federal Office for Water Management, Institute of Waters Ecology, Fisheries and Lake Research. (Ref. 87703)",
        "reference_108": "Huo, T.B., M.Y. Yuan and Z.F. Jiang0 Length-weight relationships of 23 fish species from the Ergis River in Xingjiang, China. J. Appl. Ichthyol. 27:937-938. (Ref. 88165)",
        "reference_109": "Verreycken, H., G. Van Thuyne and C. Belpaire0 Length-weight relationships of 40 freshwater fish species from two decades of monitoring in Flanders (Belgium). J. Appl. Ichthyol. 2011:1-5. (Ref. 88166)",
        "reference_110": "Sideleva, V.G.0 The endemic fishes of Lake Baikal. Backhuys Publ., Leiden, Netherlands, 270 p. (Ref. 92309)",
        "reference_111": "Grabowska, J., J. Kotusz and A. Witkowski0 Alien invasive fish species in Polish waters: an overview. Folia Zool. 59(1):73-85. (Ref. 92885)",
        "reference_112": "European Network on Invasive Alien Species (NOBANIS)0 NOBANIS (Gateway to information on Invasive Alien species in North and Central Europe. NOBANIS (Ref. 93375)",
        "reference_113": "Petriki, O., E. Gousia and D.C. Bobori0 Weight-length relationships of 36 fish species from the River Strymon system (northern Greece). J. Appl. Ichthyol. 27(3):939-941. (Ref. 95340)",
        "reference_114": "FAO-FIES0 Aquatic Sciences and Fisheries Information System (ASFIS) species list. Retrieved from http://www.fao.org/fishery/collection/asfis/en, April 2014. (Ref. 95632)",
        "reference_115": "Jawad, L.A., A. Al-Faisal and M. Al-Mukhtar0 Presence of the non-indegenous fish species, Gibel carp, <i>Carassius gibelio</i> (Family: Cyprinidae) in Basrah Province freshwater systems, Iraq. Water Research and Management 2(4):41-44. (Ref. 97262)",
        "reference_116": "FAO-FIES0 Aquatic Sciences and Fisheries Information System (ASFIS) species list. Retrieved from http://www.fao.org/fishery/collection/asfis/en, [accessed 13/04/2015]. (Ref. 101110)",
        "reference_117": "Pihu, E.0 Loomade elu 4. köide. Kalad. Pihu, E. 1979. Loomade Elu, 4. Köide, Kalad. Valgus, Tallinn. (Ref. 105472)",
        "reference_118": "Çiçek, E., R. Fricke and S.S. Birecikligil0 Freshwater fishes of Turkey: a revised and updated annotated checklist. Biharean Biologist 9(2):141-157. (Ref. 106151)",
        "reference_119": "Liu, M.H., R.D. Fang, J.P. Zhao and K. Wang0 Length-weight relationship for five fish species from Jingpo Lake, Heilongjiang, China. J. Appl. Ichthyol. 32:151-152. (Ref. 108863)",
        "reference_120": "Semenchenko, V.P., V.K. Rizevsky, S.E. Mastitsky, V.V. Vezhnovets, M.V. Pluta, V.I. Razlutsky and T. Laenko0 Checklist of aquatic alien species established in large river basins of Belarus. Aquatic Invasions 4(2): 337-347. (Ref. 115062)",
        "reference_121": "FAO-FIES0 Aquatic Sciences and Fisheries Information System (ASFIS) species list. Retrieved from http://www.fao.org/fishery/collection/asfis/en (accessed 08/06/2017). (Ref. 115257)",
        "reference_122": "Moreno-Valcárcel, R., F.J. Oliva-Paterna, C. Arribas and C. Fernández-Delgado0 Length-weight relationships for 13 fish species collected in the Doñana marshlands (Guadalquivir estuary, SW Spain). J. Appl. Ichthyol. 28:663-664. (Ref. 115878)",
        "reference_123": "Radkhah, A. and S. Eagderi0 Length-weight and length-length relationships and condition factor of six cyprinid fish species from Zarrineh River (Urmia Lake basin, Iran). Iran J. Ichthyol. 2(1):61-64. (Ref. 118451)",
        "reference_124": "Dgebuadze, Y.Y.0 Fishery and freshwater ecosystems of Russia:  status, trends, research, management and priorities. p. 120-133. In J.F. Craig (ed.).  Freshwater Fisheries Ecology. John Wiley & Sons Ltd. 899p. (Ref. 119200)",
        "reference_125": "Elgin, E.L., H.R. Tunna and L.J. Jackson0 First confirmed records of Prussian carp, <i>Carassius gibelio</i> (Bloch, 1782) in open waters of North America. BioInvasions Records 3(Issue 4):275-282. (Ref. 120696)",
        "reference_126": "Halas, D., N. Lovejoy and N.E. Mandrak0 Undetected diversity of goldfish (<i>Carassius</i> spp.) in North America. Aquatic Invasions 13(2):211-219. (Ref. 120697)",
        "reference_127": "Reis, I., H. Cerim and C. Ates0 Length-Weight relationship of 13 fish species from the Lower Sakarya River, Turkey. Aquat. Sci. Eng. 34(3):86-89. (Ref. 121682)",
        "reference_128": "Tammiksaar, E. and K. Kangur0 Fish and fishing in Lake Peipsi (Estonia/Russia) since 1851: Similarities and differences between historical and modern times. J. Great Lakes Res. 46(2020):862-869. (Ref. 122793)",
        "reference_129": "Dhora, D.0 Updated lists of the fish species of Albania's freshwater. Bul. Shk. Ser. Shk. Nat. 2020(70):46-74. (Ref. 125501)",
        "reference_130": "Marčeta, B. and K. Pliberšek (eds)0 BiosWeb. Biological database of the Fisheries Research Institute of Slovenia. Ljubljana, Fisheries Research Institute of Slovenia, 2014. (www.biosweb.org. updated 13/04/2023). (Ref. 128520)",
        "reference_131": "Keskin, A. and D. Pauly0 Testing predictions of length at first maturity of teleostean fishes, given their maximum length. Cybium 47(3):249-257. (Ref. 131385)",
        "reference_132": "Saç, G. and H. Okgerman0 Growth and reproduction of a non-native fish species <i>Carassius gibelio</i> (Bloch, 1782) from Büyükçekmece Lake (İstanbul, Turkey). IUFS J. Biol. 74(1):1-12. (Ref. 131424)",
        "identifier_2": "FB-pic-6376-48351",
        "dataType": "http://purl.org/dc/dcmitype/StillImage",
        "mimeType": "image/jpeg",
        "agent": "Information Center Chinese Academy of Fishery Sciences",
        "created_2": "2008-03-04",
        "modified_2": "2010-07-13",
        "license": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rights": "This work is licensed under a Creative Commons Attribution-Noncommercial 3.0 Unported License. Image can be freely copied and altered but may be used only for non-commercial purposes. Original author and source must be properly acknowledged",
        "rightsHolder": "WorldFish Center - FishBase",
        "audience": "General public",
        "source_2": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats",
        "mediaURL": "https://www.fishbase.org/images/species/Cagib_u2.jpg",
        "thumbnailURL": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u2.jpg",
        "identifier_3": "FB-pic-6376-48352",
        "dataType_2": "http://purl.org/dc/dcmitype/StillImage",
        "mimeType_2": "image/jpeg",
        "agent_2": "Information Center Chinese Academy of Fishery Sciences",
        "created_3": "2008-03-04",
        "modified_3": "2008-03-06",
        "license_2": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rights_2": "This work is licensed under a Creative Commons Attribution-Noncommercial 3.0 Unported License. Image can be freely copied and altered but may be used only for non-commercial purposes. Original author and source must be properly acknowledged",
        "rightsHolder_2": "WorldFish Center - FishBase",
        "audience_2": "General public",
        "source_3": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_2": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat",
        "mediaURL_2": "https://www.fishbase.org/images/species/Cagib_u3.jpg",
        "thumbnailURL_2": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u3.jpg",
        "identifier_4": "FB-pic-6376-48353",
        "dataType_3": "http://purl.org/dc/dcmitype/StillImage",
        "mimeType_3": "image/jpeg",
        "agent_3": "Information Center Chinese Academy of Fishery Sciences",
        "created_4": "2008-03-04",
        "modified_4": "2008-03-04",
        "license_3": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rights_3": "This work is licensed under a Creative Commons Attribution-Noncommercial 3.0 Unported License. Image can be freely copied and altered but may be used only for non-commercial purposes. Original author and source must be properly acknowledged",
        "source_4": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "mediaURL_3": "https://www.fishbase.org/images/species/Cagib_u4.jpg",
        "thumbnailURL_3": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u4.jpg",
        "identifier_5": "FB-pic-6376-48354",
        "dataType_4": "http://purl.org/dc/dcmitype/StillImage",
        "mimeType_4": "image/jpeg",
        "agent_4": "Information Center Chinese Academy of Fishery Sciences",
        "created_5": "2008-03-04",
        "modified_5": "2008-03-06",
        "license_4": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rights_4": "This work is licensed under a Creative Commons Attribution-Noncommercial 3.0 Unported License. Image can be freely copied and altered but may be used only for non-commercial purposes. Original author and source must be properly acknowledged",
        "rightsHolder_3": "WorldFish Center - FishBase",
        "audience_3": "General public",
        "source_5": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_3": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Morphology",
        "mediaURL_4": "https://www.fishbase.org/images/species/Cagib_u5.jpg",
        "thumbnailURL_4": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u5.jpg",
        "identifier_6": "FB-pic-6376-48355",
        "dataType_5": "http://purl.org/dc/dcmitype/StillImage",
        "mimeType_5": "image/jpeg",
        "agent_5": "Information Center Chinese Academy of Fishery Sciences",
        "created_6": "2008-03-04",
        "modified_6": "2008-03-06",
        "license_5": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rights_5": "This work is licensed under a Creative Commons Attribution-Noncommercial 3.0 Unported License. Image can be freely copied and altered but may be used only for non-commercial purposes. Original author and source must be properly acknowledged",
        "rightsHolder_4": "WorldFish Center - FishBase",
        "audience_4": "General public",
        "source_6": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_4": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution",
        "mediaURL_5": "https://www.fishbase.org/images/species/Cagib_u6.jpg",
        "thumbnailURL_5": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u6.jpg",
        "identifier_7": "FB-GeneralDescr-6376",
        "dataType_6": "http://purl.org/dc/dcmitype/Text",
        "mimeType_6": "text/html",
        "agent_6": "Rainer Froese",
        "created_7": "1992-08-31 00:00:00",
        "modified_7": "2024-01-25 00:00:00",
        "title": "Biology",
        "license_6": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_5": "WorldFish Center - FishBase",
        "audience_5": "General public",
        "source_7": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_5": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Uses",
        "description": "Inhabits a wide variety of still water bodies and lowland rivers, usually associated with submerged vegetation or regular flooding.  Can strongly tolerate low oxygen concentrations and pollution (Ref. 59043).  Lake dwelling individuals move into river mouths to avoid low oxygen water in winter (Ref. 39176).  Feeding larvae and juveniles occur in high-complexity habitats as reed belts.  Feeds on plankton, benthic invertebrates, plant material and detritus.  Spawns in shallow, warm shores on submerged vegetation (Ref. 59043).  Able to reproduce from unfertilized eggs (gynogenesis) (Ref. 41851).  Life span reaches up to about 10 years (Ref. 59043).  Eastern European or wild form of the goldfish (Ref. 1739).",
        "reference_133": "Kottelat, M. and J. Freyhof 2007 Handbook of European freshwater fishes. Publications Kottelat, Cornol and Freyhof, Berlin. 646 pp. (Ref. 59043)",
        "identifier_8": "FB-DiagnosticDescr-6376",
        "dataType_7": "http://purl.org/dc/dcmitype/Text",
        "mimeType_7": "text/html",
        "agent_7": "Armi G. Torres",
        "created_8": "2010-05-01 00:00:00",
        "modified_8": "2010-05-01 00:00:00",
        "license_7": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_6": "WorldFish Center - FishBase",
        "audience_6": "General public",
        "source_8": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_6": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#TrophicStrategy",
        "description_2": "Diagnosed from its congeners in Europe by having the following characters:  body silvery-brown in color; last simple anal and dorsal rays strongly serrated; 37-52 gill rakers; lateral line with 29-33 scales; freed edge of dorsal concave or straight; anal fin with 5½ branched rays; and peritoneum black (Ref. 59043).",
        "reference_134": "Kottelat, M. and J. Freyhof 2007 Handbook of European freshwater fishes. Publications Kottelat, Cornol and Freyhof, Berlin. 646 pp. (Ref. 59043)",
        "identifier_9": "FB-Distribution-6376",
        "dataType_8": "http://purl.org/dc/dcmitype/Text",
        "mimeType_8": "text/html",
        "agent_8": "Rainer Froese",
        "created_9": "1992-08-31 00:00:00",
        "modified_9": "2019-07-26 00:00:00",
        "license_8": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_7": "WorldFish Center - FishBase",
        "audience_7": "General public",
        "source_9": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_7": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Size",
        "description_3": "Europe and Asia:  usually considered as native from central Europe to Siberia or introduced to European waters from eastern Asia.  Clear and definite data on original distribution in Europe are not available due to introduction, confusion with Carassius auratus and complex modes of reproduction.  At present, widely distributed and commonly stocked together with Cyprinus carpio which is transported throughout Europe.  Absent in northern Baltic basin, Iceland, Ireland, Scotland and Mediterranean islands.",
        "reference_135": "Kottelat, M. and J. Freyhof 2007 Handbook of European freshwater fishes. Publications Kottelat, Cornol and Freyhof, Berlin. 646 pp. (Ref. 59043)",
        "identifier_10": "FB-Uses-6376",
        "dataType_9": "http://purl.org/dc/dcmitype/Text",
        "mimeType_9": "text/html",
        "agent_9": "Rainer Froese",
        "created_10": "1992-08-31 00:00:00",
        "modified_10": "2024-01-25 00:00:00",
        "title_2": "Importance",
        "license_9": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_8": "WorldFish Center - FishBase",
        "audience_8": "General public",
        "source_10": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_8": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats",
        "description_4": "fisheries: minor commercial",
        "reference_136": "Muus, B.J. and P. Dahlström 1968 Süßwasserfische. BLV Verlagsgesellschaft, München. 224 p. (Ref. 556)",
        "identifier_11": "FB-Migration-6376",
        "dataType_10": "http://purl.org/dc/dcmitype/Text",
        "mimeType_10": "text/html",
        "agent_10": "Rainer Froese",
        "created_11": "1992-08-31 00:00:00",
        "modified_11": "2024-01-25 00:00:00",
        "license_10": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_9": "WorldFish Center - FishBase",
        "audience_9": "General public",
        "source_11": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_9": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat",
        "description_5": "Potamodromous. Migrating within streams, migratory in rivers, e.g. Saliminus, Moxostoma, Labeo.  Migrations should be cyclical and predictable and cover more than 100 km.",
        "reference_137": "Riede, K. 2004 Global register of migratory species - from global to regional scales. Final Report of the R&D-Projekt 808 05 081. Federal Agency for Nature Conservation, Bonn, Germany. 329 p. (Ref. 51243)",
        "identifier_12": "FB-LifeCycle-6376",
        "dataType_11": "http://purl.org/dc/dcmitype/Text",
        "mimeType_11": "text/html",
        "agent_11": "Tom Froese",
        "created_12": "1992-08-31 00:00:00",
        "modified_12": "2024-01-25 00:00:00",
        "license_11": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_10": "WorldFish Center - FishBase",
        "audience_10": "General public",
        "source_12": "http://www.fishbase.org//Reproduction/FishReproSummary.php?ID=6376&StockCode=6695",
        "subject_10": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution",
        "description_6": "Females spawn with several other species, for example Cyprinus carpio and Carassius carassius, but the eggs just develop without being actually fertilized resulting in a female only population (Ref. 2059). In Europe, populations considered as triploid and only females. But in some populations, it should be possible to find up to 25% of males which should be diploid (Ref. 40476). \"There are also all-female populations in which all individuals are triploids.  Triploids are sperm parasites of other cyprinid species such as Cyprinus carpio, Rutilus rutilus and Abramis brama.  Older individuals spawn earlier in season than younger ones. Males move to spawning sites before females.  Males follow ripe females, often with much splashing.  Sticky eggs are attached to water plants or submerged objects\" (Ref. 59043).",
        "reference_138": "Baensch, H.A. and R. Riehl 1991 Aquarien atlas. Bd. 3. Melle: Mergus, Verlag für Natur-und Heimtierkunde, Germany. 1104 p. (Ref. 2059)",
        "identifier_13": "FB-Size-6376",
        "dataType_12": "http://purl.org/dc/dcmitype/Text",
        "mimeType_12": "text/html",
        "agent_12": "Rainer Froese",
        "created_13": "1992-08-31 00:00:00",
        "modified_13": "2024-01-25 00:00:00",
        "title_3": "Max. size",
        "license_12": "http://creativecommons.org/licenses/by-nc/3.0/",
        "source_13": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "description_7": "46.6 cm TL (male/unsexed; (Ref. 88166)); max. published weight: 3,000 g (Ref. 556); max. reported age: 10 years (Ref. 59043)",
        "reference_139": "Verreycken, H., G. Van Thuyne and C. Belpaire 2011 Length-weight relationships of 40 freshwater fish species from two decades of monitoring in Flanders (Belgium). J. Appl. Ichthyol. 2011:1-5. (Ref. 88166)",
        "reference_140": "Muus, B.J. and P. Dahlström 1968 Süßwasserfische. BLV Verlagsgesellschaft, München. 224 p. (Ref. 556)",
        "reference_141": "Kottelat, M. and J. Freyhof 2007 Handbook of European freshwater fishes. Publications Kottelat, Cornol and Freyhof, Berlin. 646 pp. (Ref. 59043)",
        "identifier_14": "FB-Threats-2",
        "dataType_13": "http://purl.org/dc/dcmitype/Text",
        "mimeType_13": "text/html",
        "agent_13": "Belen Acosta",
        "created_14": "1990-10-18 00:00:00",
        "modified_14": "2024-03-07 00:00:00",
        "license_13": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_11": "WorldFish Center - FishBase",
        "audience_11": "General public",
        "source_14": "http://www.fishbase.org/summary/SpeciesSummary.php?id=2",
        "subject_11": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Size",
        "description_8": "Least Concern (LC) , IUCN Grouper and Wrasse Specialist Group",
        "reference_142": "IUCN 2006 2006 IUCN red list of threatened species. www.iucnredlist.org. Downloaded July 2006.",
        "identifier_15": "FB-Diseases-6376-35",
        "dataType_14": "http://purl.org/dc/dcmitype/Text",
        "mimeType_14": "text/html",
        "agent_14": "Allan Palacio",
        "created_15": "2004-10-13 00:00:00",
        "modified_15": "2004-10-13 00:00:00",
        "license_14": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_12": "WorldFish Center - FishBase",
        "audience_12": "General public",
        "source_15": "http://www.fishbase.org/diseases/diseasesList.cfm?ID=6376&StockCode=6695",
        "subject_12": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats",
        "description_9": "Black Spot Disease 1. Parasitic infestations (protozoa, worms, etc.)",
        "reference_143": "Ondrackova, M., P. Jurajda and M. Gelnar 2002 The distribution of <i>Posthodiplostomum cuticola</i> metacercariae in young-of-the-year cyprinid fishes. J. Fish Biol. 60(5):1355-1357. (Ref. 47806)",
        "identifier_16": "FB-Diseases-6376-949",
        "dataType_15": "http://purl.org/dc/dcmitype/Text",
        "mimeType_15": "text/html",
        "agent_15": "Allan Palacio",
        "created_16": "2003-06-25 00:00:00",
        "modified_16": "2003-06-25 00:00:00",
        "license_15": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_13": "WorldFish Center - FishBase",
        "audience_13": "General public",
        "source_16": "http://www.fishbase.org/diseases/diseasesList.cfm?ID=6376&StockCode=6695",
        "subject_13": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat",
        "description_10": "Thelohanellus Infection 4. Parasitic infestations (protozoa, worms, etc.)",
        "reference_144": "Wang, G.T., W.J. Yao, J.G. Wang and Y.S. Lu 2001 Occurrence of thelohanellosis caused by <i>Thelohanellus wuhanensis</i> (Mysoxporea) in juvenile allogynogenetic silver crucian carp, <i>Carassius auratus gibelio</i> (Bloch), with an observation on the efficacy of fumagillin as a therapeutant. J. Fish Dis. 24:57-60. (Ref. 47459)",
        "identifier_17": "FB-Habitat-6376",
        "dataType_16": "http://purl.org/dc/dcmitype/Text",
        "mimeType_16": "text/html",
        "agent_16": "Rainer Froese",
        "created_17": "1992-08-31 00:00:00",
        "modified_17": "2024-01-25 00:00:00",
        "title_4": "Environment",
        "license_16": "http://creativecommons.org/licenses/by-nc/3.0/",
        "rightsHolder_14": "WorldFish Center - FishBase",
        "audience_14": "General public",
        "source_17": "http://www.fishbase.org/summary/SpeciesSummary.php?id=6376",
        "subject_14": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution",
        "description_11": "benthopelagic; potamodromous (Ref. 51243); freshwater; brackish; pH range: 7.1 - 7.5; dH range: 12; depth range 0 - ? m",
        "reference_145": "Riede, K. 2004 Global register of migratory species - from global to regional scales. Final Report of the R&D-Projekt 808 05 081. Federal Agency for Nature Conservation, Bonn, Germany. 329 p. (Ref. 51243)",
        "DisplayName": "Carassius gibelio (Bloch, 1782)",
        "images": [
            "https://www.fishbase.org/images/species/Cagib_u2.jpg",
            "https://www.fishbase.org/images/species/Cagib_u3.jpg",
            "https://www.fishbase.org/images/species/Cagib_u4.jpg",
            "https://www.fishbase.org/images/species/Cagib_u5.jpg",
            "https://www.fishbase.org/images/species/Cagib_u6.jpg"
        ],
        "primary_image": "https://www.fishbase.org/images/species/Cagib_u2.jpg"
    },
    "primary": {
        "primary_image": {
            "url": "https://www.fishbase.org/images/species/Cagib_u2.jpg",
            "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u2.jpg",
            "description": null,
            "agent": {
                "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                "@logoURL": "",
                "@role": "photographer",
                "#text": "Information Center Chinese Academy of Fishery Sciences"
            },
            "license": "http://creativecommons.org/licenses/by-nc/3.0/",
            "created": "2008-03-04",
            "identifier": "FB-pic-6376-48351"
        },
        "primary_text": {
            "title": "Biology",
            "description": "Inhabits a wide variety of still water bodies and lowland rivers, usually associated with submerged vegetation or regular flooding.  Can strongly tolerate low oxygen concentrations and pollution (Ref. 59043).  Lake dwelling individuals move into river mouths to avoid low oxygen water in winter (Ref. 39176).  Feeding larvae and juveniles occur in high-complexity habitats as reed belts.  Feeds on plankton, benthic invertebrates, plant material and detritus.  Spawns in shallow, warm shores on submerged vegetation (Ref. 59043).  Able to reproduce from unfertilized eggs (gynogenesis) (Ref. 41851).  Life span reaches up to about 10 years (Ref. 59043).  Eastern European or wild form of the goldfish (Ref. 1739).",
            "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Uses",
            "agent": {
                "@homepage": "http://www.fishbase.de/rfroese",
                "@logoURL": "",
                "@role": "recorder",
                "#text": "Rainer Froese"
            },
            "created": "1992-08-31 00:00:00",
            "modified": "2024-01-25 00:00:00",
            "identifier": "FB-GeneralDescr-6376"
        },
        "primary_description": {
            "title": "Biology",
            "description": "Inhabits a wide variety of still water bodies and lowland rivers, usually associated with submerged vegetation or regular flooding.  Can strongly tolerate low oxygen concentrations and pollution (Ref. 59043).  Lake dwelling individuals move into river mouths to avoid low oxygen water in winter (Ref. 39176).  Feeding larvae and juveniles occur in high-complexity habitats as reed belts.  Feeds on plankton, benthic invertebrates, plant material and detritus.  Spawns in shallow, warm shores on submerged vegetation (Ref. 59043).  Able to reproduce from unfertilized eggs (gynogenesis) (Ref. 41851).  Life span reaches up to about 10 years (Ref. 59043).  Eastern European or wild form of the goldfish (Ref. 1739).",
            "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Uses",
            "agent": {
                "@homepage": "http://www.fishbase.de/rfroese",
                "@logoURL": "",
                "@role": "recorder",
                "#text": "Rainer Froese"
            },
            "created": "1992-08-31 00:00:00",
            "modified": "2024-01-25 00:00:00",
            "identifier": "FB-GeneralDescr-6376"
        },
        "images": [
            {
                "url": "https://www.fishbase.org/images/species/Cagib_u2.jpg",
                "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u2.jpg",
                "description": null,
                "agent": {
                    "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                    "@logoURL": "",
                    "@role": "photographer",
                    "#text": "Information Center Chinese Academy of Fishery Sciences"
                },
                "license": "http://creativecommons.org/licenses/by-nc/3.0/",
                "created": "2008-03-04",
                "identifier": "FB-pic-6376-48351"
            },
            {
                "url": "https://www.fishbase.org/images/species/Cagib_u3.jpg",
                "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u3.jpg",
                "description": null,
                "agent": {
                    "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                    "@logoURL": "",
                    "@role": "photographer",
                    "#text": "Information Center Chinese Academy of Fishery Sciences"
                },
                "license": "http://creativecommons.org/licenses/by-nc/3.0/",
                "created": "2008-03-04",
                "identifier": "FB-pic-6376-48352"
            },
            {
                "url": "https://www.fishbase.org/images/species/Cagib_u4.jpg",
                "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u4.jpg",
                "description": null,
                "agent": {
                    "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                    "@logoURL": "",
                    "@role": "photographer",
                    "#text": "Information Center Chinese Academy of Fishery Sciences"
                },
                "license": "http://creativecommons.org/licenses/by-nc/3.0/",
                "created": "2008-03-04",
                "identifier": "FB-pic-6376-48353"
            },
            {
                "url": "https://www.fishbase.org/images/species/Cagib_u5.jpg",
                "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u5.jpg",
                "description": null,
                "agent": {
                    "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                    "@logoURL": "",
                    "@role": "photographer",
                    "#text": "Information Center Chinese Academy of Fishery Sciences"
                },
                "license": "http://creativecommons.org/licenses/by-nc/3.0/",
                "created": "2008-03-04",
                "identifier": "FB-pic-6376-48354"
            },
            {
                "url": "https://www.fishbase.org/images/species/Cagib_u6.jpg",
                "thumbnail": "https://www.fishbase.org/images/thumbnails/jpg/tn_Cagib_u6.jpg",
                "description": null,
                "agent": {
                    "@homepage": "https://www.fishbase.org/collaborators/CollaboratorSummary.php?id=1573",
                    "@logoURL": "",
                    "@role": "photographer",
                    "#text": "Information Center Chinese Academy of Fishery Sciences"
                },
                "license": "http://creativecommons.org/licenses/by-nc/3.0/",
                "created": "2008-03-04",
                "identifier": "FB-pic-6376-48355"
            }
        ],
        "descriptions": [
            {
                "title": "Biology",
                "description": "Inhabits a wide variety of still water bodies and lowland rivers, usually associated with submerged vegetation or regular flooding.  Can strongly tolerate low oxygen concentrations and pollution (Ref. 59043).  Lake dwelling individuals move into river mouths to avoid low oxygen water in winter (Ref. 39176).  Feeding larvae and juveniles occur in high-complexity habitats as reed belts.  Feeds on plankton, benthic invertebrates, plant material and detritus.  Spawns in shallow, warm shores on submerged vegetation (Ref. 59043).  Able to reproduce from unfertilized eggs (gynogenesis) (Ref. 41851).  Life span reaches up to about 10 years (Ref. 59043).  Eastern European or wild form of the goldfish (Ref. 1739).",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Uses",
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-GeneralDescr-6376"
            },
            {
                "title": null,
                "description": "Diagnosed from its congeners in Europe by having the following characters:  body silvery-brown in color; last simple anal and dorsal rays strongly serrated; 37-52 gill rakers; lateral line with 29-33 scales; freed edge of dorsal concave or straight; anal fin with 5½ branched rays; and peritoneum black (Ref. 59043).",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#TrophicStrategy",
                "agent": {
                    "@homepage": "",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Armi G. Torres"
                },
                "created": "2010-05-01 00:00:00",
                "modified": "2010-05-01 00:00:00",
                "identifier": "FB-DiagnosticDescr-6376"
            },
            {
                "title": null,
                "description": "Europe and Asia:  usually considered as native from central Europe to Siberia or introduced to European waters from eastern Asia.  Clear and definite data on original distribution in Europe are not available due to introduction, confusion with Carassius auratus and complex modes of reproduction.  At present, widely distributed and commonly stocked together with Cyprinus carpio which is transported throughout Europe.  Absent in northern Baltic basin, Iceland, Ireland, Scotland and Mediterranean islands.",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Size",
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2019-07-26 00:00:00",
                "identifier": "FB-Distribution-6376"
            },
            {
                "title": "Importance",
                "description": "fisheries: minor commercial",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats",
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-Uses-6376"
            },
            {
                "title": null,
                "description": "Potamodromous. Migrating within streams, migratory in rivers, e.g. Saliminus, Moxostoma, Labeo.  Migrations should be cyclical and predictable and cover more than 100 km.",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat",
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-Migration-6376"
            },
            {
                "title": null,
                "description": "Females spawn with several other species, for example Cyprinus carpio and Carassius carassius, but the eggs just develop without being actually fertilized resulting in a female only population (Ref. 2059). In Europe, populations considered as triploid and only females. But in some populations, it should be possible to find up to 25% of males which should be diploid (Ref. 40476). \"There are also all-female populations in which all individuals are triploids.  Triploids are sperm parasites of other cyprinid species such as Cyprinus carpio, Rutilus rutilus and Abramis brama.  Older individuals spawn earlier in season than younger ones. Males move to spawning sites before females.  Males follow ripe females, often with much splashing.  Sticky eggs are attached to water plants or submerged objects\" (Ref. 59043).",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution",
                "agent": {
                    "@homepage": "",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Tom Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-LifeCycle-6376"
            },
            {
                "title": "Max. size",
                "description": "46.6 cm TL (male/unsexed; (Ref. 88166)); max. published weight: 3,000 g (Ref. 556); max. reported age: 10 years (Ref. 59043)",
                "subject": null,
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-Size-6376"
            },
            {
                "title": null,
                "description": "Least Concern (LC) , IUCN Grouper and Wrasse Specialist Group",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Size",
                "agent": {
                    "@homepage": "",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Belen Acosta"
                },
                "created": "1990-10-18 00:00:00",
                "modified": "2024-03-07 00:00:00",
                "identifier": "FB-Threats-2"
            },
            {
                "title": null,
                "description": "Black Spot Disease 1. Parasitic infestations (protozoa, worms, etc.)",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats",
                "agent": {
                    "@homepage": "",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Allan Palacio"
                },
                "created": "2004-10-13 00:00:00",
                "modified": "2004-10-13 00:00:00",
                "identifier": "FB-Diseases-6376-35"
            },
            {
                "title": null,
                "description": "Thelohanellus Infection 4. Parasitic infestations (protozoa, worms, etc.)",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat",
                "agent": {
                    "@homepage": "",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Allan Palacio"
                },
                "created": "2003-06-25 00:00:00",
                "modified": "2003-06-25 00:00:00",
                "identifier": "FB-Diseases-6376-949"
            },
            {
                "title": "Environment",
                "description": "benthopelagic; potamodromous (Ref. 51243); freshwater; brackish; pH range: 7.1 - 7.5; dH range: 12; depth range 0 - ? m",
                "subject": "http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution",
                "agent": {
                    "@homepage": "http://www.fishbase.de/rfroese",
                    "@logoURL": "",
                    "@role": "recorder",
                    "#text": "Rainer Froese"
                },
                "created": "1992-08-31 00:00:00",
                "modified": "2024-01-25 00:00:00",
                "identifier": "FB-Habitat-6376"
            }
        ],
        "videos": [],
        "sounds": []
    },
    "api_info": {
        "token_name": "Aadish_unlimited",
        "requests_used": 27,
        "rate_limit": "Unlimited"
    }
}

function findFishByName(fishName) {
  if (!fishName) return undefined;
  console.log("Found data loadingscreen:", data);

  return data
}

export default function LoadingScreen() {
  const location = useLocation();
  const navigate = useNavigate();
  const fishName = location.state?.fishName;

  useEffect(() => {
    // Simulate a fetch/search
    const data = findFishByName(fishName);
    setTimeout(() => {
      navigate("/fishinfo", { state: { data } });
    }, 300);
  }, [fishName, navigate]);

  return <div>Loading...</div>;
}
